POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "user02",
    "password": "12345"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "user01",
    "password": "1234"
}