POST http://localhost:3030/api/auth/register
Content-Type: application/json

{
    "email": "",
    "username": "user01",
    "password": "1234"
}

###

POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
    "username": "user02",
    "password": "12345"
}

###

POST http://localhost:3030/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhlYmJhNzZlYzRlNTU3MTQ3YjhlMTUiLCJpYXQiOjE2NzA0MDg5OTN9.HveNnc9veEJIyy_wzMtWyw7CA5K2CPTwezW_VWpaX6U

{
    "title": "my fourth lesson",
    "description": "learn spring",
    "url": "spring.io",
    "status": "TO LEARN"
}

###

GET http://localhost:3030/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhlYmJhNzZlYzRlNTU3MTQ3YjhlMTUiLCJpYXQiOjE2NzA4MzU1NTF9.EClNT74usBssMOnEN-tnQyW0JxPEC2k4eNrEgQEu5w8

###
PUT http://localhost:3030/api/posts/63906b84ff76e93f19e74ad
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhlYmJhNzZlYzRlNTU3MTQ3YjhlMTUiLCJpYXQiOjE2NzA4MzQ4OTR9.TH8bAFe3UNg3GqVfu9F1rrokEgBg5-0B2MudOzXs9k8

{
    "title": "second post",
    "description": "learn struts",
    "url": "https://struts.apache.org",
    "status": "LEARNED"
}