POST http://localhost:3030/api/auth/register
Content-Type: application/json

{
    "email": "",
    "username": "user01",
    "password": "1234"
}

###

POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
    "username": "user01",
    "password": "1234"
}

###

POST http://localhost:3030/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhjNWRlOTZkYjFiMzkzOGFhNTdjZWQiLCJpYXQiOjE2NzAxNDM1ODJ9.VcT-8UAPkdRjBeN-9_DRLe4FefjvBfvtqz2GHQW6Ef0

{
    "title": "my second lesson",
    "description": "learn react",
    "url": "reactjs.org",
    "status": "LEARNING"
}

###

GET http://localhost:3030/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzVjZTQ5MDg3MTZlNzRhZGJjOWZhNGYiLCJpYXQiOjE2NjcwMzM5NzN9.kA4yCVsERTys_ZkACnJgvNjzK9tjnA3y_HEFGPx5rDY

###
PUT http://localhost:3030/api/posts/635ce75ccdfeb3b6ecef80ca
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzVjZTQ5MDg3MTZlNzRhZGJjOWZhNGYiLCJpYXQiOjE2NjcwMzM5NzN9.kA4yCVsERTys_ZkACnJgvNjzK9tjnA3y_HEFGPx5rDY

{
    "title": "my second post",
    "description": "learned struts",
    "url": "https://struts.apache.org",
    "status": "LEARNED"
}